[qthuynh1@c7-qthuynh1 as1]$ ./CheckA1.py 
Please enter your email user id:qthuynh1

== Preliminary A1 Test Run Report for qthuynh1==
The following is your preliminary test run report for assignment 1. Please review the report and fix all the errors identified before submitting your algorithm, python script, and test report to blackboard using the assignment 1 submission link which will be available on Monday, October 7, 2019.

========================================
Test run command 1 : python3 a1_qthuynh1.py 2018/01/01 1
--test passed--
Test run command 2 : python3 a1_qthuynh1.py 2018/01/01 -1
--test failed--
---- expect: 2017/12/31
----  given: 20171231
Test run command 3 : python3 a1_qthuynh1.py 2018/01/01 2
--test passed--
Test run command 4 : python3 a1_qthuynh1.py --step 2018/01/01 3
Traceback (most recent call last):
  File "a1_qthuynh1.py", line 194, in <module>
    dbda(date,days)
  File "a1_qthuynh1.py", line 111, in dbda
    result = afer(result)
NameError: name 'afer' is not defined
--test failed--
---- expect: 2018/01/02
2018/01/03
2018/01/04
----  given: 
Test run command 5 : python3 a1_qthuynh1.py 2018/07/01 500
--test passed--
Test run command 6 : python3 a1_qthuynh1.py 2018/99/01 2
Traceback (most recent call last):
  File "a1_qthuynh1.py", line 194, in <module>
    dbda(date,days)
  File "a1_qthuynh1.py", line 114, in dbda
    result = after(result)
  File "a1_qthuynh1.py", line 44, in after
    if tmp_day > mon_max[month]:
KeyError: 99
--test failed--
---- expect: Error: wrong month entered
----  given: 
Test run command 7 : python3 a1_qthuynh1.py 2018/01/99 2
--test failed--
---- expect: Error: wrong day entered
----  given: 2018/02/08
Test run command 8 : python3 a1_qthuynh1.py 2018 2
Traceback (most recent call last):
  File "a1_qthuynh1.py", line 194, in <module>
    dbda(date,days)
  File "a1_qthuynh1.py", line 114, in dbda
    result = after(result)
  File "a1_qthuynh1.py", line 44, in after
    if tmp_day > mon_max[month]:
KeyError: 0
--test failed--
---- expect: Error: wrong date entered
----  given: 
Test run command 9 : python3 a1_qthuynh1.py 2020/02/28 1
--test passed--
Test run command 10 : python3 a1_qthuynh1.py 2020/03/01 -1
--test failed--
---- expect: 2020/02/29
----  given: 20200229
Test Results: {1: 1, 2: 0, 3: 1, 4: 0, 5: 1, 6: 0, 7: 0, 8: 0, 9: 1, 10: 0}
Total test run marks:  19.200000000000003
Total marks for script (max. 48): 19.200000000000003

